[package]
name = "openai-http-proxy"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
hyper-rustls = "0.24.0"
http = "0.2.9"
