server:
  ip: "127.0.0.1"
  port: 8000

database:
  user: "dev"
  password: "1234qwer_"
  host: "pgm-uf6v72wptlx73p9dbo.rwlb.rds.aliyuncs.com"
  port: 5432
  database: "readbot_test"
  max_connection: 8

authing:
  app_secret: 20c9149848e5986fc84bf57451c12e4f

user_service:
  app_store_password: 08db393f5cc349f499925ea04d2a44f0
