[default]
address = "127.0.0.1"
port = 8000

[mysql]
url = "mysql://root:1234@localhost:3306"
database = "feedbox_dev"

[auth_service.jwt]
access_key = "access_secret_key"
access_expiration_hour = 168 # 7 days
refresh_key = "refresh_secret_key"
refresh_expiration_hour =  720 # 30 days
