[default]
address = "127.0.0.1"
port = 8000

[database]
url = "postgres://postgres:1234@localhost:5432"
database = "feedbox_dev"
max_connection = 8

[auth_service.jwt]
access_key = "access_secret_key"
access_expiration_hour = 168 # 7 days
refresh_key = "refresh_secret_key"
refresh_expiration_hour =  720 # 30 days

[content_service]
fetch_interval_hour = 2

[user_content_service]
max_page_size = 50
