[default]
address = "127.0.0.1"
port = 8000

[mysql]
url = "mysql://root:1234@localhost:3306"
database = "feedbox_dev"

[jsonwebtoken]
access_secret_key = "access_secret_key"
access_expiration_hour = 168 # 7 days
refresh_secret_key = "refresh_secret_key"
refresh_expiration_hour =  720 # 30 days

[feed]
default_name = '未命名'
default_logo = 'https://c-ssl.duitang.com/uploads/blog/202105/09/20210509012315_89541.jpeg'